version: '3.7'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    # env_file:
    #   - 'env.influxdb'
    # environment:
    #   - PRE_CREATE_DB=sensit
    networks:
      - monitoring
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    # env_file:
    #   - 'env.grafana'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    networks:
      - monitoring
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana
  
  opentsdb:
    hostname: otsdb
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    networks:
      - monitoring
    volumes:  
      - "/srv/docker/opentsdb/data:/data/hbase"

networks:
  monitoring: